chromium: Fix a typo causing build errors for the native parts
Change
  DEPEND:append:runtime-llvm
to
  DEPENDS:append:runtime-llvm

This fixes a build errors like this below, due to the clang-native
not having been pulled in:

| In file included from ../../third_party/protobuf/src/google/protobuf/arenaz_sampler.cc:31:
| ../../third_party/protobuf/src/google/protobuf/arenaz_sampler.h:34:10: fatal error: 'atomic' file not found
| #include <atomic>
|          ^~~~~~~~
| 1 error generated.

Signed-off-by: Zoltán Böszörményi <zboszor@gmail.com>